--[[
Author: du 1149464651@qq.com
Date: 2022-12-03 17:03:18
LastEditors: du 1149464651@qq.com
LastEditTime: 2022-12-04 01:01:35
FilePath: \solid-panorama-example\addon\game\solid-example\scripts\vscripts\game_mode.lua
Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
--]]
---
--- Generated by Luanalysis
--- Created by cfj.
--- DateTime: 2022/12/3 17:03
---
GameRules.EquipList = LoadKeyValues("scripts/npc/equip_list.txt")
print('GameRules.EquipList ', GameRules.EquipList )